name: discord
base: core22
adopt-info: discord
summary: Chat for Communities and Friends
description: |
  Discord is the easiest way to communicate over voice, video and text.
  Chat, hang out, and stay close with your friends and communities.

grade: stable
confinement: strict
assumes:
- snapd2.54

architectures:
  - build-on: amd64
compression: lzo

parts:
  disable-updater:
    plugin: nil
    override-pull: |
      cat <<'EOF' > disable-updater.sh
      #!/bin/bash
      if [ ! -d "$SNAP_USER_DATA"/.config/discord ]; then
        mkdir -p "$SNAP_USER_DATA"/.config/discord
      fi
      CONFIG_FILE="$SNAP_USER_DATA"/.config/discord/settings.json
      if ! [ -f "$CONFIG_FILE" ]; then
        echo '{}' > "$CONFIG_FILE"
      fi
      ORIG_JSON=$(cat "$CONFIG_FILE")
      NEW_JSON=$(jq '.SKIP_HOST_UPDATE = true' < "$CONFIG_FILE")
      if [ "$ORIG_JSON" != "$NEW_JSON" ]; then
        echo "$NEW_JSON" > "$CONFIG_FILE"
      fi
      exec "$@"
      EOF
    override-build: |
      install -m755 -D -t $CRAFT_PART_INSTALL/bin disable-updater.sh
    stage-packages:
      - jq

  launcher:
    plugin: dump
    source: launcher
    override-build: |
      cp launcher $CRAFT_PART_INSTALL/

  discord:
    plugin: nil
    override-build: |
      craftctl default
      DEB_API="https://discord.com/api/download?platform=linux&format=deb"
      DEB_URL=$(curl -w "%{url_effective}\n" -I -L -s -S "${DEB_API}" -o /dev/null)
      curl -o discord.deb $DEB_URL
      dpkg-deb -xv discord.deb $CRAFT_PART_INSTALL/
      VERSION=$(echo "${DEB_URL}" | cut -d'/' -f6)
      craftctl set version=$(echo $VERSION)
      rm $CRAFT_PART_INSTALL/usr/share/discord/chrome-sandbox
      # Correct path to icon.
      sed -i 's|Icon=discord|Icon=/usr/share/discord/discord\.png|' ${CRAFT_PART_INSTALL}/usr/share/discord/discord.desktop
    build-packages:
      - curl
      - sed
    stage-packages:
      - libatomic1
      - libc++1
      - libnspr4
      - libnss3
      - libxss1
      - xdg-utils
    prime:
      - -usr/bin/xdg-open

  cleanup:
    after: [discord]
    plugin: nil
    build-snaps: [ gnome-42-2204 ]
    override-prime: |
        set -eux
        cd /snap/gnome-42-2204/current
        find . -type f,l -exec rm -f $CRAFT_PRIME/{} \;

plugs:
  shmem:
    interface: shared-memory
    private: true

apps:
  discord:
    extensions: [gnome]
    command: launcher
    command-chain: [bin/disable-updater.sh]
    autostart: discord.desktop
    desktop: usr/share/applications/discord.desktop
    environment:
      # Correct the TMPDIR path for Chromium Framework/Electron to
      # ensure libappindicator has readable resources
      TMPDIR: $XDG_RUNTIME_DIR
      GTK_USE_PORTAL: 1
      DISABLE_WAYLAND: 1
    plugs:
      - audio-playback
      - audio-record
      - camera
      - home
      - mount-observe
      - network
      - network-observe
      - opengl
      - process-control
      - removable-media
      - screen-inhibit-control
      - shmem
      - system-observe
      - unity7
